app/controllers/catalog_controller.rb, app/helpers/blacklight/url_helper_behavior.rb, app/views/catalog/_home_text.html.erb, app/views/catalog/_index_header_default.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_header_navbar.html.erb
closes #107
@nnunn I don't recall if you said we should remove the cookie stuff of leave it in.  Let me know what works for you.
=> carry lib parameter for branding into catalog show

config/environments/production.rb
=> add config for mailer

config/libraries.yml
=> updating northern lakes college urls

.github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/Feature_request.md
Copied the existing ones from ualbertalib/discovery. Also removed a pesky development.log
closes #193
=> add issue templates

.editorconfig
Similar to work done on discovery here: https://github.com/ualbertalib/discovery/pull/1338
=> Add editorconfig dot file so everyone has consistent coding styles

app/views/catalog/citation.html.erb
@seanluyk Is this what you were thinking?
=> add citation caution text

app/views/catalog/_home_text.html.erb, app/views/shared/_header_navbar.html.erb, db/schema.rb
=> Remove Beta labelling from app

CHANGELOG.md, app/controllers/catalog_controller.rb, app/views/catalog/_index_header_default.html.erb, app/views/catalog/_show_header_default.html.erb
=> Remove subtitle display

CHANGELOG.md, config/libraries.yml
=> update NLC Library url to new website

CHANGELOG.md
=> update changelog for 1.0.52

CHANGELOG.md
- Update changelog for NEOS Discovery 1.0.53.
=> update changelog for neosdiscovery 1.0.53

CHANGELOG.md, config/locations.yml
- Removed zero width space characters from link
#286
=> Update link to Concordia Lutheran Seminary Library

CHANGELOG.md
Update the changelog version to prepare for 1.0.54 release.
=> update changelog for 1.0.54

CHANGELOG.md
Prepare for new release 1.0.55.
=> updated changelog to prepare for release 1.0.55

CHANGELOG.md, config/locations.yml
https://search-test.library.ualberta.ca/catalog/6777842
=> aginternet was mistakenly removed in last change to this file.

CHANGELOG.md, config/locales/blacklight.en.yml
=> change application name to change open search description

CHANGELOG.md, app/views/forms/show.html.erb
== Warnings ==
Confidence: High
Category: Dynamic Render Path
Check: Render
Message: Render path contains parameter value
Code: render(action => params[:id], {})
File: app/views/forms/show.html.erb
Line: 3
=> Resolved brakeman warning

CHANGELOG.md, config/application.rb
=> bump CHANGELOG and VERSION for 1.0.62 release

CHANGELOG.md, config/application.rb, config/blacklight.yml
Prepare for 1.0.65 release
Updated CHANGELOG and application.rb version.
=> bump CHANGELOG and VERSION for 1.0.65 release

CHANGELOG.md, config/application.rb, config/blacklight.yml, config/database.yml, config/environments/staging.rb, config/secrets.yml
Prepare for 1.0.66 release
* Updated CHANGELOG and application.rb version.
* Revert Solr config
* Introduce staging environment
=> Revert Solr config change and Bump for 1.0.66

CHANGELOG.md, config/application.rb
Prepare for 1.0.67 release
Updated CHANGELOG and application.rb version.
=> bump CHANGELOG and VERSION for 1.0.67 release

CHANGELOG.md, config/application.rb
Prepare for 1.0.71 release
Updated CHANGELOG and application.rb version.
=> Bump CHANGELOG and VERSION for 1.0.71 release

CHANGELOG.md, config/application.rb
Prepare for 1.0.77 release
Updated CHANGELOG and application.rb version.
=> Bump CHANGELOG and VERSION for 1.0.77 release
